#!/bin/sh

killall -9 sxhkd dunst polybar volumeicon nm-applet blueman-applet

killall -9 picom; picom &
dunst &
lxsession &
sxhkd -c /home/wc/.config/sxhkd/sxhkdrc &
sxhkd -c /home/wc/.config/sxhkd/bspwmkeys &
$HOME/.config/polybar/launch.sh &
blueman-applet &
nm-applet &
volumeicon &

bspc rule -r "*"

bspc monitor -d 1 2 3 4 5 6

bspc config automatic_scheme longest_side
bspc config initial_polarity second_child

bspc config pointer_modifier lock
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config normal_border_color "#65737E"
bspc config active_border_color "#1e1e1e"
bspc config focused_border_color "#EFF1F5"
bspc config presel_feedback_color "#EFF1F5"
bspc config urgent_border_color "#dd2727"

bspc config top_padding 32
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 2
bspc config window_gap 10

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Gimp desktop='^5' state=floating follow=on
bspc rule -a discord desktop='4' follow=on
bspc rule -a Screenkey manage=off
