# Shell variables
# Generated by 'wal'
wallpaper='/home/wc/Pictures/wallhaven-5dvv57.jpg'

# Special
background='#040918'
foreground='#89cedb'
cursor='#89cedb'

# Colors
color0='#040918'
color1='#5E3293'
color2='#1D678E'
color3='#A621B7'
color4='#E615E7'
color5='#A674CB'
color6='#1597A6'
color7='#89cedb'
color8='#5f9099'
color9='#5E3293'
color10='#1D678E'
color11='#A621B7'
color12='#E615E7'
color13='#A674CB'
color14='#1597A6'
color15='#89cedb'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
