--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/wc/Pictures/wallhaven-5dvv57.jpg"

-- Special
background="#040918"
foreground="#89cedb"
cursor="#89cedb"

-- Colors
color0="#040918"
color1="#5E3293"
color2="#1D678E"
color3="#A621B7"
color4="#E615E7"
color5="#A674CB"
color6="#1597A6"
color7="#89cedb"
color8="#5f9099"
color9="#5E3293"
color10="#1D678E"
color11="#A621B7"
color12="#E615E7"
color13="#A674CB"
color14="#1597A6"
color15="#89cedb"
