#!/usr/bin/env bash
# shellcheck disable=SC2034
# This issue is ignored because it is part of a larger file that calls upon all variables listed

BROWSER="${BROWSER:-brave}"

# dmbook config
declare -A options
options[IP Location Finder]="https://websiteseochecker.com/ip-location"
options[Markdown Cheatsheet]="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet"
options[Minecraft Books]="https://shop.minecraft.net/collections/books"
